# Generated by Django 3.2.19 on 2023-08-17 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Quiz',
            fields=[
                ('u_quiz_id', models.AutoField(db_column='uquiz_id', primary_key=True, serialize=False)),
                ('u_content', models.CharField(max_length=200)),
                ('u_answer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ManyToManyField(db_column='user_id', related_name='user_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_quiz',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(db_column='quiz_id', primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.BooleanField(default=False)),
                ('result', models.BooleanField(default=False)),
                ('user_id', models.ManyToManyField(db_column='user_id', related_name='quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
    ]
